data:
    root: ../data/CokeDataset
    ann_file: 20190517_Coke.json
    train_all: false
    batch_size: 16
    classes: 5
    class_names: [
        background,
        kinect,
        bottle,
        cola_can,
        liquid_soap
    ]
arch: drn_d_22
optimizer:
    lr: 0.001
    momentum: 0.99
    weight_decay: 0.0001
training:
    experiment_name: drn_d_22_Coke
    resume: pretrained/drn_d_22_Coke/checkpoint_00000100.pth.tar
