data:
    root: data/kinect1_mask
    pcd_root: objects
    num_subsets: 10
    val_subset_num: 101
    objects: [
        kinect,
        bottle,
        cola_can,
        liquid_soap
    ]
    batch_size: 32
    workers: 4
arch:
    num_input_channels: 1
    num_shared_fc_layers: 1
    num_shared_fc_nodes: 256
    num_position_fc_layers: 1
    num_position_fc_nodes: 256
    num_orientation_fc_layers: 1
    num_orientation_fc_nodes: 256
loss: points # l1 | posecnn | points_simple | points
optimizer:
    lr: 0.01
    lr_decay_epochs: [700, 1400]
    momentum: 0.9
    weight_decay: 0.0001
training:
    logs_dir: logs/
    checkpoints_dir: checkpoints/
    experiment_name: kinect1_mask
    print_freq: 10
    checkpoint_epochs: 100
    epochs: 3100
    log_dir:
    resume:
