data:
    root: data/kinect1_mask
    num_subsets: 10
    val_subset_num: 101
    objects: [
        kinect,
        bottle,
        cola_can,
        liquid_soap
    ]
    batch_size: 32
arch:
    num_input_channels: 1
    num_shared_fc_layers: 1
    num_shared_fc_nodes: 256
    num_position_fc_layers: 1
    num_position_fc_nodes: 256
    num_orientation_fc_layers: 1
    num_orientation_fc_nodes: 256
    num_position_outputs: 12
    num_orientation_outputs: 16
loss: points # l1 | posecnn | points_simple | points
optimizer:
    lr: 0.01
    lr_decay_epochs: [700, 1400]
    momentum: 0.9
    weight_decay: 0.0001
training:
    experiment_name: floating_kinect1_mask
    resume: pretrained/floating_kinect1_mask/checkpoint_00002100.pth.tar
